ISPITNI/apartments/Models/Entities/City.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models.Entities
{
    public class City : BaseEntity
    {
        public string Name { get; set; }
        public float Country { get; set; }

        public virtual List<Apartment> Apartments { get; set; } =new List<Apartment>();
    
    }
}

ISPITNI/apartments/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using WebApplication1.Models.Entities;

namespace WebApplication1.Controllers
{
    [Authorize(Roles = "admin,user")]
    public class CitiesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Cities
        [Authorize(Roles ="user,admin")]
        public ActionResult Index()
        {
            return View(db.Cities.ToList());
        }

        // GET: Cities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // GET: Cities/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cities/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Country")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Cities.Add(city);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(city);
        }

        // GET: Cities/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: Cities/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Country")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Entry(city).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(city);
        }

        // GET: Cities/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: Cities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            City city = db.Cities.Find(id);
            city.Apartments.ForEach(a => a.CityID = null);
            city.Apartments.ForEach(a => a.IsAvailable = true);
            db.Cities.Remove(city);
            db.SaveChanges();
            return RedirectToAction("Index");
        }



        public ActionResult AddApartmanToCity(int? cityId)
        {
            if (cityId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ViewBag.CityId = cityId;
            ViewBag.CityName = db.Cities.Find(cityId).Name;


         

            var availableApartmants = db.Apartmants
                                  .Where(a => a.IsAvailable)
                                  .ToList();

            ViewBag.ApartmanId = new SelectList(availableApartmants, "Id", "Name");

            return View();
        }

        // POST: Doctors/AddPatient
        [HttpPost]

        public ActionResult AddApartmanToCity(int? CityID, int? ApartmanId)
        {
            if (CityID == null || ApartmanId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var city = db.Cities.Find(CityID);
            var apartman = db.Apartmants.Find(ApartmanId);

            if (city == null || apartman == null)
            {
                return HttpNotFound();
            }

            city.Apartments.Add(apartman);
            apartman.IsAvailable = false;

            try
            {
                db.SaveChanges();
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors)
                {
                    Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                        eve.Entry.Entity.GetType().Name, eve.Entry.State);
                    foreach (var ve in eve.ValidationErrors)
                    {
                        Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                            ve.PropertyName, ve.ErrorMessage);
                    }
                }
                throw; // Rethrow the exception to handle it further up the stack if needed
            }

            return RedirectToAction("Details", new { id = CityID });
        }


        //[HttpPost]
        public ActionResult RemoveApartman(int? CityID, int? ApartmanId)
        {
            if (CityID == null || ApartmanId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var city = db.Cities.Find(CityID);
            var apartman = db.Apartmants.Find(ApartmanId);

            if (city == null || apartman == null)
            {
                return HttpNotFound();
            }

            city.Apartments.Remove(apartman);
            apartman.IsAvailable = true;

            try
            {
                db.SaveChanges();
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors)
                {
                    Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                        eve.Entry.Entity.GetType().Name, eve.Entry.State);
                    foreach (var ve in eve.ValidationErrors)
                    {
                        Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                            ve.PropertyName, ve.ErrorMessage);
                    }
                }
                throw; // Rethrow the exception to handle it further up the stack if needed
            }

            return RedirectToAction("Details", new { id = CityID });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ISPITNI/apartments/Views/Cities/AddApartmanToCity.cshtml
@model WebApplication1.Models.Entities.Apartment

@{
    ViewBag.Title = "Add Apartman";
}

<h2>Add Apartman for @ViewBag.CityName</h2>

@using (Html.BeginForm("AddApartmanToCity", "Cities"))
{
    @Html.Hidden("CityID", (int)ViewBag.CityID)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
        @Html.DropDownList("ApartmanID", null, "-- Select Apartman --", new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-primary">Add Patient</button>
}

ISPITNI/apartments/Views/Cities/Create.cshtml
@model WebApplication1.Models.Entities.City

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>City</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ISPITNI/apartments/Views/Cities/Delete.cshtml
@model WebApplication1.Models.Entities.City

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>City</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ISPITNI/apartments/Views/Cities/Details.cshtml
@model WebApplication1.Models.Entities.City

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>City</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

    </dl>
</div>


<div>
    <h4>Associated Apartmans</h4>
    <hr />
    <table class="table">
        <tr>
            <th>Apartman Name</th>
            <th>Apartman Adress</th>
            <th>PricePerDay</th>
            <th>Actions</th>
        </tr>
        @foreach (var apartman in Model.Apartments)
        {
            if (apartman.City != null)
            {
                <tr>
                    <td>@apartman.Name</td>
                    <td>@apartman.Address</td>
                    <td>@apartman.PricePerDay</td>

                    <td>
                        @Html.ActionLink("Remove", "RemoveApartman", new { cityID = Model.ID, apartmanID = apartman.ID })
                    </td>
                </tr>
            }
            else
            {
    <div>
        <span>NO APARTMANs STILL FOR @Model.Name</span>
    </div>
             
            }
        }
    </table>
</div>




@Html.ActionLink("ADD A NEW APARTMAN", "AddApartmanToCity", new { cityId = Model.ID })

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ISPITNI/apartments/Views/Cities/Edit.cshtml
@model WebApplication1.Models.Entities.City

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>City</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ISPITNI/apartments/Views/Cities/Index.cshtml
@model IEnumerable<WebApplication1.Models.Entities.City>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table id="cityTable" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Country)
                </td>
                <td>
                    @if (User.IsInRole("admin"))
                    {
                        <div>
                            @Html.ActionLink("Edit", "Edit", new { id = item.ID })
                        </div>
                      
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                    }
                    else
                    {
                    @Html.ActionLink("Details", "Details", new { id = item.ID })
                    }
                </td>
            </tr>
        }
    </tbody>
</table>