LAB3_HospitalSystem/HospitalSystem/HospitalSystem/Models/Entities/Hospital.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HospitalSystem.Models.Entities
{
    public class Hospital : BaseEntity
    {
        [Required]
        public string HospitalName { get; set; }
        [Required]
        public string HospitalLocation { get; set; }
        [Required]
        public string HospitalImage { get; set; }
        public virtual ICollection<Doctor> Doctors { get; set; } = new List<Doctor>();
    }
}

LAB3_HospitalSystem/HospitalSystem/HospitalSystem/Controllers/HospitalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HospitalSystem.Models;
using HospitalSystem.Models.Entities;

namespace HospitalSystem.Controllers
{
    //[Authorize(Roles ="Administrator")]
    public class HospitalsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Hospitals
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View(db.Hospitals.ToList());
        }

        // GET: Hospitals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hospital hospital = db.Hospitals
                                 .Include(h => h.Doctors)
                                 .FirstOrDefault(d => d.Id == id);


            if (hospital == null)
            {
                return HttpNotFound();
            }
            return View(hospital);
        }

        // GET: Hospitals/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Hospitals/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,HospitalName,HospitalLocation,HospitalImage")] Hospital hospital)
        {
            if (ModelState.IsValid)
            {
                db.Hospitals.Add(hospital);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(hospital);
        }

        // GET: Hospitals/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hospital hospital = db.Hospitals.Find(id);
            if (hospital == null)
            {
                return HttpNotFound();
            }
            return View(hospital);
        }

        // POST: Hospitals/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,HospitalName,HospitalLocation,HospitalImage")] Hospital hospital)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hospital).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hospital);
        }

        // GET: Hospitals/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hospital hospital = db.Hospitals.Find(id);
            if (hospital == null)
            {
                return HttpNotFound();
            }
            return View(hospital);
        }

        // POST: Hospitals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Hospital hospital = db.Hospitals.Find(id);

            if (hospital == null)
            {
                return HttpNotFound();
            }

            //  disassociate doctors from this hospital now
            var doctors = db.Doctors.Where(d => d.HospitalId == id).ToList();
            foreach (var doctor in doctors)
            {
                doctor.HospitalId = null; // Disassociate doctor from hospital making it null
            }

            db.Hospitals.Remove(hospital);
            db.SaveChanges();

            return RedirectToAction("Index");
        }



       
        public ActionResult AddDoctor(int? hospitalId)
        {
            if (hospitalId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ViewBag.HospitalId =  hospitalId;
            ViewBag.HospitalName = db.Hospitals.Find(hospitalId).HospitalName;
            var doctors = db.Doctors.Where(dr => dr.HospitalId == null).ToList();
            ViewBag.DoctorId = new SelectList(doctors, "Id", "DoctorName");

            return View();
        }

        // POST: Doctors/AddPatient
        [HttpPost]

        public ActionResult AddDoctor(int? hospitalId, int? doctorId)
        {
            if (hospitalId == null || doctorId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var hospital = db.Hospitals.Find(hospitalId);
            var doctor = db.Doctors.Find(doctorId);

            if (hospital == null || doctor == null)
            {
                return HttpNotFound();
            }

                hospital.Doctors.Add(doctor);
                db.SaveChanges();
         
            return RedirectToAction("Details", new { id = hospitalId });
        }



        public ActionResult RemoveDoctor(int? hospitalId, int? doctorId)
        {
            if (hospitalId == null || doctorId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            var hospital = db.Hospitals.Find(hospitalId);
            var doctor = db.Doctors.Find(doctorId);
            doctor.HospitalId = null;

            hospital.Doctors.Remove(doctor);
            db.SaveChanges();

            return RedirectToAction("Details", new { id = hospitalId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LAB3_HospitalSystem/HospitalSystem/HospitalSystem/Views/Hospitals/AddDoctor.cshtml
@model HospitalSystem.Models.Entities.Doctor

@{
    ViewBag.Title = "Add Doctor";
}

<h2>Add Patient for @ViewBag.HospitalName</h2>

@using (Html.BeginForm("AddDoctor", "Hospitals"))
{
    @Html.Hidden("HospitalId", (int)ViewBag.HospitalId)

    <div class="form-group">
        @Html.LabelFor(model => model.DoctorName, htmlAttributes: new { @class = "control-label" })
        @Html.DropDownList("DoctorId", null, "-- Select Doctor --", new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-primary">Add Doctor</button>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LAB3_HospitalSystem/HospitalSystem/HospitalSystem/Views/Hospitals/Create.cshtml
@model HospitalSystem.Models.Entities.Hospital

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Hospital</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.HospitalName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HospitalName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HospitalName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HospitalLocation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HospitalLocation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HospitalLocation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HospitalImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HospitalImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HospitalImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LAB3_HospitalSystem/HospitalSystem/HospitalSystem/Views/Hospitals/Delete.cshtml
@model HospitalSystem.Models.Entities.Hospital

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Hospital</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HospitalName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HospitalName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HospitalLocation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HospitalLocation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HospitalImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HospitalImage)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LAB3_HospitalSystem/HospitalSystem/HospitalSystem/Views/Hospitals/Details.cshtml
@model HospitalSystem.Models.Entities.Hospital

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Hospital</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HospitalName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HospitalName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HospitalLocation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HospitalLocation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HospitalImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HospitalImage)
        </dd>

    </dl>
</div>

<p>
    @Html.ActionLink("Add Doctor", "AddDoctor", new { hospitalId = Model.Id })
</p>

<div>
    <h4>Associated Doctors</h4>
    <hr />
    <table class="table">
        <tr>
            <th>Doctor Name</th>
            <th>#Patients</th>
            <th>Actions</th>
        </tr>
        @foreach (var patientDoctor in Model.Doctors)
        {
            if (patientDoctor != null)
            {
                <tr>
                    <td>@patientDoctor.DoctorName</td>
                    <td>@patientDoctor.Patients.Count</td>
                
                    <td>
                        @Html.ActionLink("Remove", "RemoveDoctor", new { hospitalId = Model.Id, doctorId = patientDoctor.Id })
                    </td>
                </tr>
            }
        }
    </table>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LAB3_HospitalSystem/HospitalSystem/HospitalSystem/Views/Hospitals/Edit.cshtml
@model HospitalSystem.Models.Entities.Hospital

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Hospital</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.HospitalName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HospitalName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HospitalName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HospitalLocation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HospitalLocation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HospitalLocation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HospitalImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HospitalImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HospitalImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LAB3_HospitalSystem/HospitalSystem/HospitalSystem/Views/Hospitals/Index.cshtml
@model IEnumerable<HospitalSystem.Models.Entities.Hospital>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table id="hospitalTable" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.HospitalName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HospitalLocation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HospitalImage)
            </th>
            <th></th>
        </tr>

    </thead>
   
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.HospitalName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HospitalLocation)
                </td>
                <td>
                    <img src="@item.HospitalImage" alt="Image" style="max-width: 200px" />
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @*@Html.ActionLink("Delete", "Delete", new { id = item.Id })*@
                    <button data-hospital-id="@item.Id" class="btn-link js-delete">Delete</button>
                </td>
            </tr>
        }

    </tbody>
</table>


@section scripts{
    <script>
        $(document).ready(function () {
            var table = $("#hospitalTable").DataTable();

            $("#hospitalTable .js-delete").on("click", function () {
                var button = $(this);
                bootbox.confirm("Do you want to delete this hospital?", function (result) {
                    if (result) {
                        $.ajax({
                            url: "/api/HospitalAPI/" + button.attr("data-hospital-id"),
                            method: "DELETE",
                            success: function () {
                                table.row(button.parents("tr")).remove().draw();
                            },
                            errror: function (err) {
                                console.log(err);
                            }
                        })
                    }
                });

            });
        });

    </script>
}